name: CI
on: 
  pull_request:
  push:
    branches: [ master ]
jobs:
  fetch:
    runs-on: ubuntu-latest
    name: Fetch libs
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - run: zig build --fetch
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - run: zig build test
