name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test-server:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
          cache: false

      - run: zig env

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
          cache: false

      - run: zig env

      - name: Run zig fmt
        if: matrix.os == 'ubuntu-latest'
        run: zig fmt --check .

      - name: Run server 
        run: |
            zig build testing-server & 
            sleep 10
            zig build test --summary all
